# Generated by Django 2.2.6 on 2019-11-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191126_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='comment',
        ),
    ]
